name: chat_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  http: ^1.0.0
  provider: ^6.0.5
  shared_preferences: ^2.0.0
  image_picker: ^0.8.6+5
  file_picker:
  audioplayers:
  flutter_colorpicker:
  image: ^3.0.5
  carousel_slider: ^4.0.0
  speech_to_text: ^6.6.0
  syncfusion_flutter_signaturepad:
  video_player:
  pdf:
  path_provider: ^2.0.11
  open_file: ^3.2.1
  flutter_pdfview:
  flutter_tts: ^3.2.2
  intl:
  fl_chart: ^0.69.0
  share_plus: ^7.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pub++++++++ section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/images/
    - assets/audios/
    - assets/images/desk/
    - assets/images/kitchen/
    - assets/videos/
    - assets/backgrounds/
    - assets/instructions/

  # example:
  fonts:
     - family: ABeeZee
       fonts:
         - asset: assets/fonts/font01/ABeeZee-Regular.ttf
         - asset: assets/fonts/font01/ABeeZee-Regular.ttf
           style: italic

     - family: Rubik
       fonts:
         - asset: assets/fonts/font02/Rubik-VariableFont_wght.ttf
         - asset: assets/fonts/font02/Rubik-Italic-VariableFont_wght.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
